### ISSUE TITLE
document libedit as build dependency (by llvm) or remove it or/and how it can be disabled (with consequences)

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig-bootstrap#125]
See in LLVM repo `./cmake/Modules/FindLibEdit.cmake` for why its a build dependency.

Can be disabled with `-DLLVM_ENABLE_LIBEDIT=off`, but I am unsure if there are bad implications for the intended use cases.

**Comment by andrewrk** [comment]
it should be disabled

**Comment by kassane** [comment]
Solution:
- https://github.com/llvm/llvm-project/issues/57573#issuecomment-1238033268

**Comment by LinuxUserGD** [comment]
See https://github.com/ziglang/zig-bootstrap/blob/a836b63c1ae8e734a0f94cc4031610adfb4bedf7/build#L150

**Comment by matu3ba** [comment]
@LinuxUserGD True, but its not disabled on the first LLVM build.
