### ISSUE TITLE
lld link error using zig-bootstrap to build zig

### ISSUE THREAD

**Issue by david-vanderson** [ziglang/zig-bootstrap#133]
This is on x86_64 linux with master zig-bootstrap and master zig.
```
~/zig-bootstrap$ ./build -j12 x86_64-linux-musl baseline
```
zig-bootstrap builds successfully.  But trying to use it to compile zig:
```
~/zig$ /home/dvanderson/zig-bootstrap/out/host/bin/zig build -p stage3 --search-prefix /home/dvanderson/zig-bootstrap/out/host --zig-lib-dir lib -Dstatic-llvm
LLD Link... ld.lld: error: undefined symbol: llvm::SubtargetFeatures::getString() const
>>> referenced by zig_llvm.cpp:101 (src/zig_llvm.cpp:101)
>>>               /home/dvanderson/zig/zig-cache/o/ee82a7ca45e2a20ff0c0a78abfce3ae5/zig_llvm.o:(ZigLLVMGetNativeFeatures)
```
followed by lots of similar link errors.  I've tried some stuff but unable to figure out what's going wrong.

Any advice for things to look at or try?

**Comment by matu3ba** [comment]
Does your system use glibc, musl or another libc?

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/issues/13138#issuecomment-1281628150

**Comment by david-vanderson** [comment]
Thank you!
