### ISSUE TITLE
stage2 can't cross compile mingw

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig-bootstrap#144]
To reproduce on Linux:
```sh-session
$ touch empty.c
$ echo "pub fn main() void {}" > main.zig
$ zig build-exe a.zig a.c -target x86_64-windows -fstage1
$ zig build-exe main.zig empty.c -target x86_64-windows
error(mingw): clang exited with code 1 and stderr: error: unknown target triple 'native-unknown-linux-gnu', please use -triple or -arch

error(mingw): clang exited with code 1 and stderr: error: unknown target triple 'native-unknown-linux-gnu', please use -triple or -arch

error: unable to generate DLL import .lib file: ClangPreprocessorFailed
```

**Comment by Vexu** [comment]
This is caused by passing native to `build`, I think it should either resolve to the canonical value or be disallowed entirely.

**Comment by alexrp** [comment]
@Vexu just to be clear, is the repro for this issue just `./build x86_64-windows native` on a Linux machine?

**Comment by Vexu** [comment]
I think it happened when using `./build native-linux-gnu native` but I haven't tried it since making this issue.

**Comment by alexrp** [comment]
Both `./build native-linux-gnu native` and `./build native-windows-gnu native` work for me on Linux.

Do you think it's safe to close this?

**Comment by Vexu** [comment]
Fine by me. I haven't ran into this since.
