### ISSUE TITLE
build failure on M1 Mac

### ISSUE THREAD

**Issue by gegogi** [ziglang/zig-bootstrap#155]
Latest zig-bootstrap (bf1b2cdb83141ad9336eec42160c9fe87f90198d) build on M1 Mac is failing.
Build command line is ```./build native-native-musl baseline```.
What could be the reason?

<img width="897" alt="Screenshot 2023-07-01 at 11 55 34 AM" src="https://github.com/ziglang/zig-bootstrap/assets/639708/5e0634e9-c899-4b55-9890-fc93712cde79">

**Comment by nektro** [comment]
error message includes potential fix, its recommending you try `./build native-native-none baseline`

but also if you're doing native-native you should follow the regular build from source instructions https://github.com/ziglang/zig/wiki/Building-Zig-From-Source instead of using zig-bootstrap

**Comment by gegogi** [comment]
Ok, I can see that now.
But what does it mean to specify 'none' for <libc> part of the triple?
Doesn't the repo contain the musl source code?

And I also wonder why it is preferred way to use zig repo instead of zig-bootstrap repo.
Isn't zig-bootstrap a collection of the safe revision of zig and needed dependencies?

**Comment by nektro** [comment]
musl is a libc implementation for linux, not macos. so trying to use it with a macos triple will not work.
