### ISSUE TITLE
Error on x86_64-linux-gnu native

### ISSUE THREAD

**Issue by prfiredragon** [ziglang/zig-bootstrap#169]
First of all my Linux is custom. The directories /lib and /usr does not exist.  I think for the information that i have found that Zig has issues finding the crt1.o. I have tried to modify the constants /lib /usr and others on the program but No luck at the moment. I don't know if exist a parameter to specify in the bootstrap where are this files . I have tried the libc.txt but don't work or I am not doing it well.  

If i can pass the arguments like with the other compilers to where are the files needed and some one can direct me to them i will appreciate it. 

this is on of the many errors.

install
└─ install generated to doc/langref.html
   └─ run docgen (langref.html)
      └─ WriteFile null.out
         └─ run doctest (test_inline_for.out) stderr
warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.
steps [284/286] zig build-exe zig ReleaseFast native-linux-gnu... LLVM Emit Object...

**Comment by alexrp** [comment]
If you're using a custom Linux, there is only so much we can do on our end, and there is really not much information to go on here.

My best guess is that it's failing to find `/usr/bin/env`, or perhaps failing to find the dynamic linker at the expected path.
