### ISSUE TITLE
slow compilation: add "-j" parameter

### ISSUE THREAD

**Issue by lars18th** [ziglang/zig-bootstrap#202]
Hi @andrewrk ,

With the current implementation, when compiling with `cmake` only one thread is in use. This is _very_ slow. But recent versions of the CMake tool supports adding `-j`. For example, every time I need to compile I replace
-   ```cmake --build . --target install```

with

-   ```cmake --build . --target install -j 8```

So, I suggest to add the option to use "-j" when calling, or inside the build script.

**Comment by alexrp** [comment]
This is why the README suggests setting the `CMAKE_BUILD_PARALLEL_LEVEL` environment variable when invoking the `build` script.

**Comment by lars18th** [comment]
> This is why the README suggests setting the `CMAKE_BUILD_PARALLEL_LEVEL` environment variable when invoking the `build` script.

Nice! However, it's not very clear. Perhaps adding a _simple_ exemple like: `CMAKE_BUILD_PARALLEL_LEVEL=8 ./build x86_64-linux-gnu baseline` could be useful. Don't think so?

**Comment by andrewrk** [comment]
it's clear enough, please just read it and comprehend it
