### ISSUE TITLE
error: unsupported linker arg: -Bsymbolic-functions

### ISSUE THREAD

**Issue by MrBrN197** [ziglang/zig-bootstrap#203]
in the step to rebuild LLVM with the zig.
llvm includes this option `-Xlinker -Bsymbolic-functions` that zig (or the linker zig is trying to use ) doesn't seem to support when compiling libclang

**Comment by alexrp** [comment]
Please give exact steps to reproduce the error.

**Comment by MrBrN197** [comment]
@alexrp sorry my fault; I was attempting to use a different llvm19/clang build from earlier than the one provided in the repository. I didn't have time to try reproduce this as the llvm build takes a long time.

**Comment by alexrp** [comment]
Note that zig-bootstrap only supports using the LLVM version that's vendored in the repository, unlike the zig repository which supports any LLVM 19.x version.
