### ISSUE TITLE
Bootstrap script fails with /bin/sh -> dash

### ISSUE THREAD

**Issue by heidezomp** [ziglang/zig-bootstrap#22]
Trying out Zig 0.6.0 (Congratulations on the release! :tada:), the bootstrap tarball fails to run by default on my Ubuntu 18.04 laptop, which apparently uses `dash` as its `/bin/sh` by default:
```
heidezomp@falafel% ./build -j1 native native
./build: 13: ./build: Bad substitution
heidezomp@falafel% ls -l /bin/sh
lrwxrwxrwx 1 root root 4 okt  2  2019 /bin/sh -> dash*
```
Changing the shebang to use `/bin/bash` works.

Not sure if this is actually a bug, but the README states this script requires a POSIX shell, which according to dash's man page, it is.

**Comment by andrewrk** [comment]
Ideally the script can be updated to be pure POSIX shell. in the meantime the readme should probably link to this issue and note that bash is accidentally required

**Comment by pingiun** [comment]
If bash is essentially required, why not change the hashbang?

**Comment by calroc** [comment]
FWIW I just downloaded zig-bootstrap-0.6.0.tar.xz and tried it on Ubuntu and got the above error.
