### ISSUE TITLE
skip LLVM rebuild if host==target?

### ISSUE THREAD

**Issue by paulsmith** [ziglang/zig-bootstrap#33]
If the $TARGET is the same as the host, could the bootstrap be greatly sped-up by skipping the rebuild of LLVM with Zig?

**Comment by daurnimator** [comment]
There is no guarantee that your existing LLVM is compiled with all the right options.

**Comment by paulsmith** [comment]
Sorry, I should have been more clear: there are two builds of LLVM in zig-bootstrap, one that uses the host’s existing compiler tool chain, and one that uses `zig c++`— I just mean skipping that latter one if the target and host are the same arch/OS.

**Comment by andrewrk** [comment]
This repo is intended more as "executable documentation" than a full featured project intending to solve everyone's use cases. I feel like the simplicity of status quo is worthwhile to this goal.
