### ISSUE TITLE
Changing the cpu features for a target does not rebuild LLVM

### ISSUE THREAD

**Issue by FireFox317** [ziglang/zig-bootstrap#35]
This is pretty big issue, because for example when you first build a zig compiler for `arm-linux-musleabi` with -mcpu being `arm1176jzf_s` and then build a zig compiler for `arm-linux-musleabi` with -mcpu being `baseline`, it does not rebuild LLVM. 

The problem is that `make` does not know that the cpu features have been updated and thus it will not rebuild LLVM. The solution would be to create a llvm directory name including the cpu features.

**Comment by andrewrk** [comment]
You mean the target llvm, not the host LLVM right? Just double checking

**Comment by FireFox317** [comment]
Yes, indeed the target LLVM.

For example here when we build the LLVM for a target, we don't include `$MCPU` into the directory name. That might be a solution.
https://github.com/ziglang/zig-bootstrap/blob/1c9ef63a4093b52eed142131e64949d87fced62f/build#L51-L54

**Comment by andrewrk** [comment]
That proposed solution sounds good.
