### ISSUE TITLE
build - bashisms in sh script (commit 1c9ef63)

### ISSUE THREAD

**Issue by drawkula** [ziglang/zig-bootstrap#39]
—▷ https://github.com/ziglang/zig-bootstrap/commit/1c9ef63a4093b52eed142131e64949d87fced62f
```
$ echo $(lsb_release -sir)
Debian 10
$ ./build -j1 arm-linux-musleabihf baseline
./build: 16: ./build: Bad substitution
$ head -1 build 
#!/bin/sh
$ awk 'NR==16' build 
TARGET_OS_CMAKE="${TARGET_OS_CMAKE/macos/Darwin}"
```
A typical `/bin/sh` doesn't support substitutions.  Is your `/bin/sh` still a link to `bash`?
```
bash ./build -j1 arm-linux-musleabihf baseline
```
...starts to run as expected.

**Comment by FireFox317** [comment]
Well, the readme mentions bash as a requirement, so it would probably be good to change the shebang line of the build script to `#!/bin/bash`
https://github.com/ziglang/zig-bootstrap/blob/59c7ecc44f52ad9b52f406a18854318e8ff897e5/README.md#L19-L24

**Comment by drawkula** [comment]
> it would probably be good to change the shebang line of the build script to `#!/bin/bash`

It not only would be good, it is the only correct way.

**Comment by andrewrk** [comment]
The dependency on BASH is a problem, and I would like to get away from depending on it. I did that commit because I thought we already depended on bash, so a couple more wouldn't hurt anything. PRs welcome to reduce or remove the dependency on bash.
