### ISSUE TITLE
deliver patches instead of patched sources

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig-bootstrap#61]
Currently, whenever we update the sources, we apply the same patches again. This is not only redundant but also making the commit log messy.
Suggestions:
1. Create a separate patch directory for storing patches.
2. Deliver patched source on release, i.e. apply patches for releases.

**Comment by andrewrk** [comment]
Closing this because I don't want there to be an extra step of applying patches after obtaining the zig-bootstrap sources. This introduces a dependency on a patching system, and complicates the build instructions.
