### ISSUE TITLE
Recent artifacts look broken

### ISSUE THREAD

**Issue by Kha** [ziglang/zig-bootstrap#70]
```
Archive: zig+llvm+lld+clang-x86_64-windows-gnu-0.9.0-dev.1249+210ef5af8.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```
This is from MSYS2 `unzip`. Explorer isn't happy either; same result for the artifact before that.

Perhaps the artifact should be zipped before uploading, as advised in the Actions warning?

**Comment by andrewrk** [comment]
I disabled the artifacts; will look into a different mechanism for delivering regular windows devkit builds.
