### ISSUE TITLE
Use Python for scripting and get this working on Windows

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig-bootstrap#74]
Currently I see no POSIX-specific utlities need to bootstrap Zig besides bash. Maybe we can switch to use Python for scripting to reduce dependencies. Another benifit for this is to be able to run this on Windows.

**Comment by Prince213** [comment]
It's attractive to run this on Windows, and it does no harm (we need Python anyway).

**Comment by nektro** [comment]
it'd be better to add a powershell/batch script for windows because otherwise the python script would need to special case windows regardless

**Comment by LinuxUserGD** [comment]
> it'd be better to add a powershell/batch script for windows because otherwise the python script would need to special case windows regardless

See https://github.com/ziglang/zig-bootstrap/pull/140

**Comment by andrewrk** [comment]
done with batch script
