### ISSUE TITLE
Update zig up to commit 496eb6927 CI: add non-LLVM backends to the test matrix

### ISSUE THREAD

**Issue by perillo** [ziglang/zig-bootstrap#84]
I'm unable to build zig using zig-bootstrap,  due to the error:

```
./test/tests.zig:668:28: error: no member named 'use_llvm' in struct 'std.build.LibExeObjStep'
                these_tests.use_llvm = false;
```

*Option A* (https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#option-a-use-your-system-installed-build-tools) does not work for me (on Archlinux), probably because of  Dual-Abi Linking.

Thanks

**Comment by nektro** [comment]
zig-bootstrap is not needed to build zig

check https://github.com/ziglang/zig/wiki/Troubleshooting-Build-Issues#arch-linux-gentoo-fedora-32

**Comment by perillo** [comment]
@nektro: Unfortunately I'm unable to build stage2 on ArchLinux:
```
LLD Link... ld.lld: error: undefined symbol: __libc_single_threaded
>>> referenced by cow-string-inst.o:(std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()) in archive /usr/lib/libstdc++.a
>>> referenced by cow-string-inst.o:(std::string::_M_mutate(unsigned long, unsigned long, unsigned long)) in archive /usr/lib/libstdc++.a
>>> referenced by cow-string-inst.o:(std::string::reserve(unsigned long)) in archive /usr/lib/libstdc++.a
>>> referenced 355 more times
error: LLDReportedFailure
```

It should be related to https://github.com/ziglang/zig/issues/11137.

Thanks.

**Comment by perillo** [comment]
https://github.com/ziglang/zig/issues/11137 resolved the problem.
I'm closing this issue; thanks.
