### ISSUE TITLE
Unable to build on linux Aarch64, requires libatomic, but cannot find it

### ISSUE THREAD

**Issue by ghost** [ziglang/zig-bootstrap#85]
You are unable to properly finish compiling zig-bootstrap on debian AND fedora linux.
(I've only included reproducible steps for fedora to keep things simplified as fedora is easier to set up)
STEPS TO REPRODUCE:
Download the iso for fedora 36 Workstation and set up a development environment with 12GB of ram and 4+ cpu cores.
```
sudo dnf update
sudo dnf groupinstall "Development Tools" "Development Libraries"
sudo dnf install clang cmake git
sudo dnf install libatomic
```

Then download bootstrap
`git clone https://github.com/ziglang/zig-bootstrap.git`

Then attempt to build
`./build -j4 native-linux-musl native`
NOTE: No, changing it to native-linux-gnu does not change the error, neither does changing the architecture to generic

And the result will be after alot of compiling - ( It does successfully at least build the stage 1 compiler..? )

```
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/nyekonyeko/zig-bootstrap/out/native-linux-musl-native/lib/libz.a
-- Up-to-date: /home/nyekonyeko/zig-bootstrap/out/native-linux-musl-native/include/zconf.h
-- Up-to-date: /home/nyekonyeko/zig-bootstrap/out/native-linux-musl-native/include/zlib.h
-- The ASM compiler identification is unknown
-- Found assembler: /home/nyekonyeko/zig-bootstrap/out/host/bin/zig
-- Warning: Did not find file Compiler/-ASM
-- clang project is enabled
-- clang-tools-extra project is disabled
-- compiler-rt project is disabled
-- cross-project-tests project is disabled
-- libc project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is enabled
-- lldb project is disabled
-- mlir project is disabled
-- openmp project is disabled
-- parallel-libs project is disabled
-- polly project is disabled
-- pstl project is disabled
-- flang project is disabled
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY) 
CMake Error at cmake/modules/CheckAtomic.cmake:59 (message):
  Host compiler appears to require libatomic, but cannot find it.
Call Stack (most recent call first):
  cmake/config-ix.cmake:374 (include)
  CMakeLists.txt:684 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by matu3ba** [comment]
See issue https://github.com/ziglang/zig/issues/10086 and pr https://github.com/ziglang/zig/pull/11828

**Comment by NyekoNyeko** [comment]
Hm hm, checks out. If pr ziglang/zig#11828[https://github.com/ziglang/zig/pull/11828] is passed through I'll test fedora again and see if this can be closed.

**Comment by matu3ba** [comment]
Suggestion to close this.
